apiVersion: apps/v1
kind: Deployment
metadata:
  name: leo-app-demo
  labels:
    app: leoflaskdemo
spec:
  replicas: 2
  selector:
    matchLabels:
       app: leoflaskdemo
  template:
    metadata:
      labels:
        app: leoflaskdemo
    spec:
      containers:
      - name: leoflaskapp
        image: leowenlu/flask:demo
        ports:
        - containerPort: 8080